# Generated by Django 2.0.5 on 2019-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visible',
            field=models.SmallIntegerField(choices=[(0, '不可见'), (1, '可见')], default=0, verbose_name='博客列表中是否可见'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visible',
            field=models.SmallIntegerField(choices=[(0, '不可见'), (1, '可见')], default=0, verbose_name='博客列表中是否可见'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='visible',
            field=models.SmallIntegerField(choices=[(0, '不可见'), (1, '可见')], default=0, verbose_name='博客列表中是否可见'),
        ),
    ]
